spring:
  application:
    name: read2write

---
spring:
  config:
    activate:
      on-profile: dev
  batch:
    jdbc:
      initialize-schema: always
#    job:
#      enabled: false
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testDb
    username: sa
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false